server.port=9090

spring.profiles.active=mysql

# Default application profile is MySQL. For local quick start without MySQL, use: -Dspring.profiles.active=h2
# MySQL settings are contained in application-mysql.properties
# H2 settings are contained in application-h2.properties