server.port=9090

spring.profiles.active=h2

# Default application profile is H2 for local quick start without requiring MySQL.
# MySQL settings are contained in application-mysql.properties
# H2 settings are contained in application-h2.properties